apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.gamePort }}
      targetPort: 7777
      protocol: UDP
      name: satisfactory-game-port
    - port: {{ .Values.service.beaconPort }}
      targetPort: 15000
      protocol: UDP
      name: satisfactory-beacon-port
    - port: {{ .Values.service.queryPort}}
      targetPort: 15777
      protocol: UDP
      name: satisfactory-query-port
  selector:
    app: {{ .Chart.Name }}
