deployment:
  env:
    AUTOPAUSE: "true"
    AUTOSAVEINTERVAL: "300"
    AUTOSAVENUM: "3"
    AUTOSAVEONDISCONNECT: "true"
    CRASHREPORT: "true"
    DEBUG: "false"
    DISABLESEASONALEVENTS: "false"
    MAXPLAYERS: "4"
    PGID: "1000"
    PUID: "1000"
    SKIPUPDATE: "false"
    STEAMBETA: "false"
  image: wolveix/satisfactory-server:latest
  resource:
    requests:
      cpu: "2"
      memory: "6Gi"
    limits:
      cpu: "4"
      memory: "8Gi"

service:
  gamePort: 7777
  beaconPort: 15000
  queryPort: 15777

persistentVolumeClaim:
  requests:
    storage: 10Gi
